---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - weir.dev
  resources:
  - processingpipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - weir.dev
  resources:
  - processingpipelines/finalizers
  verbs:
  - update
- apiGroups:
  - weir.dev
  resources:
  - processingpipelines/status
  verbs:
  - get
  - patch
  - update
