//go:build !ignore_autogenerated

/*
Copyright 2026 Guilherme Canella.

Licensed under the MIT License. See the LICENSE file at the
root of this repository for the full license text.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessingPipeline) DeepCopyInto(out *ProcessingPipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessingPipeline.
func (in *ProcessingPipeline) DeepCopy() *ProcessingPipeline {
	if in == nil {
		return nil
	}
	out := new(ProcessingPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProcessingPipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessingPipelineList) DeepCopyInto(out *ProcessingPipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProcessingPipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessingPipelineList.
func (in *ProcessingPipelineList) DeepCopy() *ProcessingPipelineList {
	if in == nil {
		return nil
	}
	out := new(ProcessingPipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProcessingPipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessingPipelineScaling) DeepCopyInto(out *ProcessingPipelineScaling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessingPipelineScaling.
func (in *ProcessingPipelineScaling) DeepCopy() *ProcessingPipelineScaling {
	if in == nil {
		return nil
	}
	out := new(ProcessingPipelineScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessingPipelineSource) DeepCopyInto(out *ProcessingPipelineSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessingPipelineSource.
func (in *ProcessingPipelineSource) DeepCopy() *ProcessingPipelineSource {
	if in == nil {
		return nil
	}
	out := new(ProcessingPipelineSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessingPipelineSpec) DeepCopyInto(out *ProcessingPipelineSpec) {
	*out = *in
	out.Source = in.Source
	out.Worker = in.Worker
	out.Scaling = in.Scaling
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessingPipelineSpec.
func (in *ProcessingPipelineSpec) DeepCopy() *ProcessingPipelineSpec {
	if in == nil {
		return nil
	}
	out := new(ProcessingPipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessingPipelineStatus) DeepCopyInto(out *ProcessingPipelineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessingPipelineStatus.
func (in *ProcessingPipelineStatus) DeepCopy() *ProcessingPipelineStatus {
	if in == nil {
		return nil
	}
	out := new(ProcessingPipelineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessingPipelineWorker) DeepCopyInto(out *ProcessingPipelineWorker) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessingPipelineWorker.
func (in *ProcessingPipelineWorker) DeepCopy() *ProcessingPipelineWorker {
	if in == nil {
		return nil
	}
	out := new(ProcessingPipelineWorker)
	in.DeepCopyInto(out)
	return out
}
